### ISSUE TITLE
Error en URL

### ISSUE THREAD

**Issue by JuanCrg90** [tombatossals/git-puesto-en-practica#1]
La url http://git.micronautas.com/ ya no direcciona a la presentación

Saludos.

**Comment by tombatossals** [comment]
Hola @JuanCrg90, gracias por informar.

Este tutorial lo alojé en su día en Google App Engine porque no había GH-Pages de GitHub, así que lo he cambiado de sitio. Ahora ya funciona:

http://tombatossals.github.io/git-puesto-en-practica  

Gracias de nuevo! Un saludo
